kathmandu_kitchen/urls.py
from django.conf.urls import url, static, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import login

from .views import HomeView
from reservation.views import ReservationView, \
    ReservationCompleteView, AcknowledgeReservataion
from blog.views import BlogView, PostView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/login/$', login,
        kwargs={"template_name": "admin/login.html"}),

    url(r'^reservation-complete/(?P<reservation_id>\d+)/$',
        ReservationCompleteView.as_view(),
        name='reservation-complete'),

    url(r'^reserve/(?P<branch_code>\w+)/$', ReservationView.as_view(),
        name='reserve'),

    url(r'^acknowledge-reservation/(?P<reservation_id>\d+)/$',
        AcknowledgeReservataion.as_view(),
        name='acknowledge-reservation'),

    url(r'^blog/$', BlogView.as_view(), name='blog'),
    url(r'^blog/(?P<slug>[\w-]+)/$', PostView.as_view(), name='blog_post'),

    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^(?P<code>\w+)/$', HomeView.as_view(), name='home'),

] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

branch/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


DAYS_OF_THE_WEEK = (
    (1, _('Monday')),
    (2, _('Tuesday')),
    (3, _('Wednesday')),
    (4, _('Thursday')),
    (5, _('Friday')),
    (6, _('Saturday')),
    (7, _('Sunday')),
)

default_accept_msg = 'Your reservation has been accepted.'
default_reject_msg = 'Your reservation has been rejected.'


class Branch(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=300)
    contact_number = models.CharField(max_length=100, blank=True)
    admin_email = models.CharField(max_length=300)

    address = models.TextField(blank=True)
    map_tag = models.TextField(blank=True)

    facebook = models.CharField(max_length=300, blank=True)
    twitter = models.CharField(max_length=300, blank=True)

    default_accept_message = models.TextField(blank=True,
                                              default=default_accept_msg)
    default_reject_message = models.TextField(blank=True,
                                              default=default_reject_msg)

    default_mail_footer = models.TextField(blank=True, default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Branches'


class OpeningHour(models.Model):
    branch = models.ForeignKey(Branch)
    day = models.IntegerField(choices=DAYS_OF_THE_WEEK)
    start_time = models.TimeField(default=None, blank=True, null=True)
    end_time = models.TimeField(default=None, blank=True, null=True)
    remarks = models.CharField(max_length=300, blank=True)

    def __str__(self):
        return '{} ({} - {})'.format(
            self.branch.name, str(self.start_time), str(self.end_time))

    class Meta:
        ordering = ['day']
        unique_together = ('day', 'branch')

menu/models.py
from django.db import models

from branch.models import Branch


class MenuCategory(models.Model):
    branch = models.ForeignKey(Branch)
    name = models.CharField(max_length=300)
    image = models.FileField(upload_to='images', null=True, blank=True,
                             default=None)

    def __str__(self):
        return self.name + ' (' + self.branch.name + ')'

    class Meta:
        verbose_name_plural = 'Menu categories'


class FoodTag(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True)
    category = models.ForeignKey(MenuCategory)
    tags = models.ManyToManyField(FoodTag, blank=True)
    image = models.FileField(upload_to='images', null=True, blank=True,
                             default=None)
    price = models.FloatField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name

templates/acknowledge-email.html
{% extends "mail_templated/base.tpl" %}
{% load i18n %}

{% block subject %}
Reservation {{ reservation.status }} for {{ reservation.date }}
{% endblock %}


{% block body %}
{% if reservation.status == 'accepted' %}{{ reservation.branch.default_accept_message }}{% else %}{{ reservation.branch.default_reject_message }}{% endif %}

{% trans 'Reservation Details' %}
------------------------------

{% trans 'Name' %}: {{ reservation.first_name }} {{ reservation.last_name }}
{% trans 'Date' %}: {{ reservation.date }}
{% trans 'Time' %}: {{ reservation.time }}
{% trans 'Number of Persons' %}: {{ reservation.persons }}
{% trans 'Contact Email' %}: {{ reservation.email }}
{% trans 'Special Request' %}:
{{ reservation.special_request }}

{{ reservation.branch.default_mail_footer }}

{% endblock %}

{% block html %}
<p>
{% if reservation.status == 'accepted' %}
{{ reservation.branch.default_accept_message }}
{% else %}
{{ reservation.branch.default_reject_message }}
{% endif %}
</p>

<h2>Reservation Details</h2>
<div><b>{% trans 'Name' %}:</b> {{ reservation.first_name }} {{ reservation.last_name }}</div>
<div><b>{% trans 'Date' %}:</b> {{ reservation.date }}</div>
<div><b>{% trans 'Time' %}:</b> {{ reservation.time }}</div>
<div><b>{% trans 'Number of Persons' %}:</b> {{ reservation.persons }}</div>
<div><b>{% trans 'Contact Email' %}:</b> {{ reservation.email }}</div>
<div><b>{% trans 'Special Request' %}:</b>
<p><pre>{{ reservation.special_request }}</pre></p>
</div>

<p><pre>
{{ reservation.branch.default_mail_footer }}
</pre><p>
{% endblock %}

templates/acknowledge-reservation.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kathmandu Kitchen</title>

    <link href="https://fonts.googleapis.com/css?family=News+Cycle:400,700|Sacramento" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/acknowledge.css' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script>
        function post(status) {
            if (status == 'rejected') {
                if (!confirm('Are you sure you want to reject this reservation?')) {
                    return;
                }
            }
            $('#status').val(status);
            $('#language').val($('input[name="language"]:checked').val());
            $('form').submit();
        }
    </script>
</head>

<body>
    {% get_current_language as LANGUAGE_CODE %}
    <header>
        <h3>Confirm reservation</h3>
    </header>
    <div class="detail name">
        <a class="detail-title">{% trans 'First name' %}</a>
        <a class="detail-info">{{ reservation.first_name }}</a>
    </div>
    <div class="detail name">
        <a class="detail-title">{% trans 'Last name' %}</a>
        <a class="detail-info">{{ reservation.last_name }}</a>
    </div>
    <div class="detail date">
        <p class="detail-title">{% trans 'Reservation date' %}</p>
        <p class="detail-info">{{ reservation.date }}</p>
    </div>
    <div class="detail time">
        <p class="detail-title">{% trans 'Reservation time' %}</p>
        <p class="detail-info">{{ reservation.time }}</p>
    </div>
    <div class="detail no-of-people">
        <p class="detail-title">{% trans 'No of people' %}</p>
        <p class="detail-info">{{ reservation.persons }}</p>
    </div>
    <div class="detail email">
        <p class="detail-title">{% trans 'Reserved by' %}</p>
        <p class="detail-info">{{ reservation.email }}</p>
    </div>
    <div class="detail request">
        <p class="detail-title">{% trans 'Special request' %}</p>
        <pre class="detail-info">{{ reservation.special_request }}</pre>
    </div>
    <div>
        <p>Reply in</p>
        <label>
            <input type="radio" name="language" value="en" {% if LANGUAGE_CODE != 'nl' %}checked{% endif %}>
            {{ 'en'|language_name_translated }}
        </label>
        <label>
            <input type="radio" name="language" value="nl" {% if LANGUAGE_CODE == 'nl' %}checked{% endif %}>
            {{ 'nl'|language_name_translated }}
        </label>
    </div>
    <div class="action-container">
        <button class="reject" onclick="post('rejected')">{% trans 'Reject' %}</button>
        <button class="accept" onclick="post('accepted')">{% trans 'Accept' %}</button>
    </div>
    <form method="post" hidden>
        {% csrf_token %}
        <input id="status" type="hidden" name="status">
        <input id="language" type="hidden" name="language" value="en">
    </form>
</body>

templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     
    {% block meta %}{% endblock %} 
     
    <title>{% block title %}Uit Eten in Best Indian Restaurant Amsterdam &amp; Zaandam | Zaanse Schans
Best Indian Restaurant Amsterdam | Uit Eten Zaandam | Zaanse Schans{% endblock %}</title>
     
    <link rel=”canonical” href=”http://kathmandukitchen.nl”/>
    <link href="https://fonts.googleapis.com/css?family=News+Cycle:400,700|Sacramento" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
    <script src="https://booking-widget.quandoo.com/index.js" data-merchant-id="40773"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>


{% block meta %}
{% if meta_information %}
<meta name="description" content="{{ meta_information.meta_description }}">
{% if meta_keywords %}
<meta name="keywords" content="{% for keyword in meta_keywords %}{{ keyword }}{% if not forloop.last %},{% endif %}{% endfor %}">
{% endif %}
{% endif %}
{% endblock %}


{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/cooking.css' %}">

<script src="{% static 'js/jquery.tinycarousel.min.js' %}"></script>
<script src="{% static 'js/home.js' %}"></script>

<script>
    let branches = [
    {% for branch in branches %}
        { 'code': "{{ branch.code }}", 'name': "{{ branch.name }}" },
    {% endfor %}
    ];

    let currentBranchCode = "{{ current_branch.code }}";
</script>
{% endblock %}

{% block body %}
<section id="landing">
    <div class="cooking">
        <div class="wrap">
            <div class="background">
                <canvas class="background-canvas"></canvas>
            </div>
        </div>
    </div>
    <header>
        <div class="ghost" id="main-menu">
            <a class="menu-item" target="_blank" href="https://www.kathmandubestellen.nl/" id="menu-order-online">{% trans 'Order Online' %}</a>
            <a href="{% url 'blog' %}" class="menu-item" id="menu-blog">{% trans 'Blog' %}</a>
            <a class="menu-item" id="menu-see-menu">{% trans 'See Menu' %}</a>
            <a class="menu-item" id="menu-opening-hours">{% trans 'Opening Hours' %}</a>
            <a class="menu-item" id="menu-make-reservations">{% trans 'Make Reservations' %}</a>
            <a class="menu-item" id="menu-contact-us">{% trans 'Contact Us' %}</a>
            <a class="hamburger-item"><i class="ion-navicon"></i></a>
        </div>
    </header>

    <div class="content">
        <div id="promo">
            <div>
                <h1>Kathmandu Kitchen</h1>
                <p>{% blocktrans %}The taste you deserve{% endblocktrans %}</p>
                <div class="order-button-container">
                    <a class="order-button" target="_blank" href="https://www.kathmandubestellen.nl/">{% trans 'Order Online' %}</a>
                </div>
            </div>
        </div>
        <!--
        <div id="location-select-wrap">
            <hr>
            <p>{% trans 'Select a location to get started' %}</p>
            {% for branch in branches %}
            <button data-branch-code="{{ branch.code }}" data-href="{% url 'home' branch.code %}">{{ branch }}</button>
            {% endfor %}
        </div>
        -->
    </div>
    <div id="config-buttons">
        <!-- button removed due to new design -->
        <!--
        <button class="change-config ghost" onclick="showConfigModal()" hidden>
            <span class="current">{{ current_branch.code }}</span>
            <span class="next">{% trans 'click to change' %}</span>
        </button>
        -->
        <div class="change-config">
            <span class="current">{{ current_language }}</span>
            {% language next_language %}
            <span class="next">{% trans 'change to' %} <a href="?language={{ next_language }}">{{ next_language|language_name_translated }}</a></span>
            {% endlanguage %}
        </div>
    </div>
    <div class="ghost" id="navigator">
        <button id="navigate-down-btn"><i class="ion-ios-arrow-down"></i></button>
    </div>
</section>

<section id="our-menu">
    <header>
        <h2>{% trans 'Our Menu' %}</h2>
    </header>
    <div class="content">
        <a class="buttons prev" href="#">&#60;</a>
        <div class="viewport">
            <ul class="overview">
                {% for category in categories %}
                <li>
                    <h3>{{ category.name }}</h3>
                    <div class="menu-items" id="menu-items-{{ category.name|slugify }}">
                        {% for fooditem in category.fooditem_set.all %}
                        <div class="menu-item">
                            <div class="menu-item-details">
                                <div class="menu-item-details-header">
                                    <h4 class="title">{{ fooditem.name|escape }}</h4>
                                    <span class="price">{% if fooditem.price %}{{ fooditem.price }}{% else %}-{% endif %}</span>
                                </div>
                                <p class="description">{{ fooditem.description|escape }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <a class="buttons next" href="#">&#62;</a>
    </div>
</section>
<section id="reservation-section">
    <div style="margin:0 auto;text-align:center;" id="quandoo-booking-widget"></div>
</section>
<section id="opening-hours-and-contact-us">
    <div id="opening-hours">
        <header>
            <h2>{% trans 'Opening Hours' %}</h2>
        </header>
        <div class="content">
            <div id="opening-hour-list">
                {% for openinghour in current_branch.openinghour_set.all %}
                <div class="opening-hour">
                    <date class="day">{{ openinghour.get_day_display }}</date>
                    <time class="open">{% if openinghour.start_time %}{{ openinghour.start_time }}{% else %}-{% endif %}</time>
                    <time class="close">{% if openinghour.end_time %}{{ openinghour.end_time }}{% else %}-{% endif %}</time>
                    <div class="remark">{{ openinghour.remarks }}</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div id="contact-us">
        <header>
            <h2>{% trans 'Contact Us' %}</h2>
        </header>
        <div class="content">
            <div id="contact-info">
                <div>
                    <div class="name">Kathmandu Kitchen</div>
                    <div class="info">
                        <i class="fa fa-location-arrow"></i>
                        <p>{{ current_branch.address }}</p>
                    </div>
                </div>
                <div class="extra">
                    <div class="info">
                        <i class="fa fa-phone"></i>
                        <p>{{ current_branch.contact_number }}</p>
                    </div>
                    <div class="info">
                        <i class="fa fa-envelope"></i>
                        <p>{{ current_branch.admin_email }}</p>
                    </div>
                </div>
            </div>
            <div id="find-us">
                <div class="title">{% trans 'Find us on' %}</div>
                <a href="{{ current_branch.facebook }}" class="find-us-on"><i class="fa fa-facebook"></i></a>
                <a href="{{ current_branch.twitter }}" class="find-us-on"><i class="fa fa-twitter"></i></a>
            </div>
            <div id="location-map">
                {{ current_branch.map_tag|safe }}
            </div>
        </div>
    </div>
</section>

<footer>
    <p>{% trans 'Copyright (c) 2017 Kathmandu Kitchen, All Rights Reserved' %}.</p>
</footer>

<div id="modal-container">
    <div class="modal" id="hamburger-modal">
        <header>
            <h2>{% trans 'Navigate' %}</h2>
            <button class="btn-close-modal"><i class="ion-ios-close-empty"></i></button>
        </header>
        <div class="content">
            <div id="main-menu-modal">
                <a class="menu-item" target="_blank" href="https://www.kathmandubestellen.nl/" id="menu-order-online">{% trans 'Order Online' %}</a>
                <a href="{% url 'blog' %}" class="menu-item" id="ham-menu-blog">{% trans 'Blog' %}</a>
                <a class="menu-item" id="ham-menu-see-menu">{% trans 'See Menu' %}</a>
                <a class="menu-item" id="ham-menu-opening-hours">{% trans 'Opening hours' %}</a>
                <a class="menu-item" id="ham-menu-reserve">{% trans 'Make Reservations' %}</a>
                <a class="menu-item" id="ham-menu-contact-us">{% trans 'Contact us' %}</a>
            </div>
        </div>
    </div>

    <div class="modal" id="config-modal">
        <header>
            <h2>{% trans 'Select location' %}</h2>
            <button class="btn-close-modal"><i class="ion-ios-close-empty"></i></button>
        </header>
        <div class="content">
            <div id="location-select-modal">
                {% for branch in branches %}
                {% if current_branch == branch %}
                <a class="active" onclick="hideConfigModal('{{ branch.code }}')">{{ branch }}</a>
                {% else %}
                <a onclick="hideConfigModal('{{branch.code}}')" href="{% url 'home' branch.code %}">{{ branch }}</a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    {% comment %}
    <div class="modal" id="our-menu-modal">
        <header>
            <h2>{% trans 'Our menu' %}</h2>
            <!-- hide search for now -->
            <!--
            <div class="search-input-container">
                <i class="ion-ios-search"></i>
                <input type="search" placeholder="{% trans 'Search' %}">
            </div>
            -->
            <button class="btn-close-modal"><i class="ion-ios-close-empty"></i></button>
        </header>
        <div class="content">
            <div class="selected-category-wrapper">
                <div class="selected-category">
                    <a id="category-name">Tandoori</a>
                    <i class="ion-chevron-down"></i>
                </div>
            </div>
            <div class="category-list">
                {% for category in categories %}
                <a data-target="#menu-items-{{ category.name|slugify }}">{{ category.name|escape }}</a>
                {% endfor %}
            </div>
            <div class="item-list">
                {% for category in categories %}
                <div class="menu-items" id="menu-items-{{ category.name|slugify }}" hidden>
                    {% for fooditem in category.fooditem_set.all %}
                    <div class="menu-item">
                        <img {% if fooditem.image %}src="{{ fooditem.image.url }}" {% else %}class="no-img"{% endif %}>

                        <div class="menu-item-details">
                            <div class="menu-item-details-header">
                                <h4 class="title">{{ fooditem.name|escape }}</h4>
                                <span class="price">{{ fooditem.price }}</span>
                            </div>
                            <p class="description">{{ fooditem.description|escape }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endcomment %}
</div>
<script src="{% static 'js/cooking.js' %}"></script>

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-54361326-1', 'auto');
ga('send', 'pageview');
</script>
{% endblock %}

templates/reservation-complete.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kathmandu Kitchen</title>

    <link href="https://fonts.googleapis.com/css?family=News+Cycle:400,700|Sacramento" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/acknowledge.css' %}">
</head>

<body>
    <header>
        <h3>{% trans 'Reservation Details' %}</h3>
    </header>
    <div class="detail name">
        <p class="detail-title">{% trans 'First name' %}</p>
        <p class="detail-info">{{ reservation.first_name }}</p>
    </div>
    <div class="detail name">
        <p class="detail-title">{% trans 'Last name' %}</p>
        <p class="detail-info">{{ reservation.last_name }}</p>
    </div>
    <div class="detail date">
        <p class="detail-title">{% trans 'Reservation date' %}</p>
        <p class="detail-info">{{ reservation.date }}</p>
    </div>
    <div class="detail time">
        <p class="detail-title">{% trans 'Reservation time' %}</p>
        <p class="detail-info">{{ reservation.time }}</p>
    </div>
    <div class="detail no-of-people">
        <p class="detail-title">{% trans 'No of people' %}</p>
        <p class="detail-info">{{ reservation.persons }}</p>
    </div>
    <div class="detail email">
        <p class="detail-title">{% trans 'Reserved by' %}</p>
        <p class="detail-info">{{ reservation.email }}</p>
    </div>
    <div class="detail request">
        <p class="detail-title">{% trans 'Special request' %}</p>
        <pre class="detail-info">{{ reservation.special_request }}</pre>
    </div>
    <p class="info">{% trans "We'll let you know about the reservation by email asap." %}</p>
    <div class="action-container" id="home-container">
        <a class="home" href="{% url 'home' %}">{% trans "Go back to website" %}</a>
    </div>
</body>

templates/reservation-mail.html
{% extends "mail_templated/base.tpl" %}

{% block subject %}
Reservation order from {{ reservation.email }}
{% endblock %}


{% block body %}
Reservation Details
------------------------------

Name: {{ reservation.first_name }} {{ reservation.last_name }}
Date: {{ reservation.date }}
Time: {{ reservation.time }}
Number of Persons: {{ reservation.persons }}
Contact Email: {{ reservation.email }}
Special Request:
{{ reservation.special_request }}

Copy this link to ackowledge:
{{ url }}
{% endblock %}

{% block html %}
<h2>Reservation Details</h2>

<div><b>Name:</b> {{ reservation.first_name }} {{ reservation.last_name }}</div>
<div><b>Date:</b> {{ reservation.date }}</div>
<div><b>Time:</b> {{ reservation.time }}</div>
<div><b>Number of Persons:</b> {{ reservation.persons }}</div>
<div><b>Contact Email:</b> {{ reservation.email }}</div>
<div><b>Special Request:</b>
<p><pre>{{ reservation.special_request }}</pre></p>
</div>
<br><br>
<a href= "{{ url }}">Click here to acknowledge</a>
{% endblock %}